server:
  port: 8080
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: first-microservices
        uri: http://localhost:8081/
        predicates:
        - Path=/first/**
      - id: second-microservices
        uri: http://localhost:8082/
        predicates:
        - Path=/second/**